fix: create example app
tiki/tiki-sdk-dart pull request #288
Opened 2023-04-20 14:08 UTC by ricardobrg

move nock dependency to dev dependencies

2023-04-20 16:13 UTC, mike-audi requested changes

2023-04-20 16:13 UTC, mike-audi commented on example/bin/example.dart
Pretty sure this is supposed to be in `example/lib` 

see here: 
https://dart.dev/tools/pub/package-layout#examples

2023-04-21 11:25 UTC, ricardobrg commented on example/bin/example.dart
You're right! Fixed that.
I have added a guard function example too in the example app code.

2023-04-24 15:05 UTC, mike-audi approved these changes

2023-04-24 15:05 UTC, merged